version: '3'

services:
  database:
    image: mongo
    container_name: database
    ports:
      - 27017:27017

  reader-container:
    build: ./File-Handler
    ports: 
      - 8081:8081
    links:
      - database
    depends_on:
      - database

 

    
  