spring:
  application:
    name: eureka-discovery-service

server:
  port: 8095

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#       defaultZone: http://localhost:8095/eureka/
      defaultZone: http://eureka-server:8095/eureka/